### ISSUE TITLE
[Discussion] How many examples do I need for training new models

### ISSUE THREAD

**Issue by Scylla2020** [deezer/spleeter#118]
I only have a basic understanding of machine learning but just interested to know the minimum number of examples I need to train a new model? 

Also, suppose I have already used spleeter to produce a 1000 acapellas, and I already have the corresponding studio acapellas, can I then go ahead and train it on these so that I could try and remove the imperfections on any other random diy acapellas?

**Comment by aidv** [comment]
It seems like the musDB dataset only contains around 150 songs, so if you have a thousand songs, you have roughly 7 times more.

**Comment by Scylla2020** [comment]
Oh okay I see, cool.

**Comment by Scylla2020** [comment]
@aidv Is there any significant benefit on using more songs for training?

**Comment by aidv** [comment]
@Scylla2020 Yes. If your dataset is too small or much of it is the same, there's a high risk of overfitting.
Overfitting basically means that the AI learns how to do replicate that specific dataset really well.
Ironically that's a good way of compressing data using AI, but not necessarily the correct way.

Anyways, I'm actually surprized that the MusDB dataset only contains 150 songs.

I want to believe that I'm wrong aobut that to be honest, it just seems unreasonable.

But hey, AI does what AI does. It's amazing.

**Comment by discordance** [comment]
Does anybody know if the pre-trained models provided via Github release have been trained using the MusDB dataset and its 150 songs, or if it was trained on a way larger dataset ? Could not find any info about the training setup of these pre-trained models.

**Comment by ravi-annaswamy** [comment]
It was trained using 20000+ songs 
Pl see pdf of paper linked on read me

With AI or ml data becomes program
That is the various situations present in the data become program conditions and solutions 

so model trained on 20,000 songs can be several orders of magnitude accurate than the model trained on 150 songs

**Comment by aidv** [comment]
I knew it. It didn't make sense for only 150 songs to produce results like that.

**Comment by ravi-annaswamy** [comment]
Having said that 150 songs contain hundreds of thousands of learning situations since short snippets are spectrogrammed and learned

So systems trained on 150 songs in diverse genres can learn quite a lot as seen in open unmix benchmark

But systems learning from
Millions of situations get way better provided architecture allows that learning

Ravi

**Comment by aidv** [comment]
@ravi-annaswamy Oh I see. So a small dataset with varying data can give similar if not equal results as a _larger_ dataset, BUT, a large dataset will nonetheless give better results no matter what.

**Comment by ravi-annaswamy** [comment]
I would not put it that way.

A large dataset of 10000 jazz standards may not be as effective as 150 songs selected across pop rock jazz and world music. Because ability to discriminate voice or stem instruments against varying backgrounds is not in the jazz only training set.

10000 songs selected across pop and rock vs
150 songs across pop and rock will definitely be better is all I said.

**Comment by Scylla2020** [comment]
@ravi-annaswamy Will I be correct to say that currently, after any sort of training with thousands of examples the results can never be completely perfect even if you throw in a song that was used as part of the training?,due to how the neural networks work,

**Comment by iskyd** [comment]
The number of songs doesn't correspond to the number training set m. You can use as training set just a part of the song with all its informations. Of course you will have for the same songs different informations that can be considered a training set, for example the intro, the verse, the chorus and so on. You can also apply some sort of distortion to the data so that you automatically create new feature without collecting more songs / parts of the songs.
What @aidv said about overfitting is not correct. Overfitting is a problem "caused" by the number of the feature and not by the number of the training set (in this case the sound taken from a song). Instead increasing the number of the training set, if you suffer of high variance (overfitting), is likely to help a lot your algorithm. 
In order to verify that you can plot the learning curve and see what happens. 
Incrementing the number of the feature didn't help only if you suffer of high bias (underfitting).

**Comment by aidv** [comment]
Thank you for giving a more in depth explanation to all of this.

So what I'm taking away from this is, and please correct me if I'm wrong: We could technically have 1000 songs, process them through 5 different effects, and each effect having 4 different settings, giving us 20000 different samples to use in our dataset.

**Comment by iskyd** [comment]
That's what distortion is about. You obviously want to apply some distortion that could then be present in the songs you want to split.

**Comment by Mixerrog** [comment]
Discordance mentioned the BEAN dataset, that contains:

    24,097 songs
    79 hours of audio stems
    majority of pop/rock songs
Is it being used by the latest Spleeter version or is there a way to download &use it for the training files if not?

Thanks, Roger

**Comment by Mixerrog** [comment]
Sorry I am late getting to this but could you please answer this --- 

Discordance mentioned the BEAN dataset, that contains:24,097 songs
79 hours of audio stems
majority of pop/rock songs

Is it being used by the latest Spleeter version or is there a way to download &use it for the training files if not?

Thanks, Roger


    On Monday, January 13, 2020, 7:13:21 AM CST, Moussallam <notifications@github.com> wrote:  
 
 
Closed #118.
