### ISSUE TITLE
[Discussion] How do i actually change the max frequency value?

### ISSUE THREAD

**Issue by vukivic** [deezer/spleeter#153]
I'm not really into python and coding in general.
I just want to change the max frequency value and i have no idea how to do it.
I would appreciate it if one of you kind souls helped me out.

**Comment by vukivic** [comment]
I also really want to train it but i also have no idea how to do it and i don't really understand the tutorials

**Comment by romi1502** [comment]
We've just updated the [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-) to provide a new way of performing separation above 11kHz.
As explained, if 16kHz is fine to you, you can straightforwardly use the packaged configs `spleeter:2stems-16kHz`, `spleeter:4stems-16kHz` and `spleeter:5stems-16kHz`.
Otherwise, you can set the `F` parameter in the json config file to `2048`. The separation will then be performed until 22kHz (be aware that it will require double RAM which may lead to OOM).

**Comment by faroit** [comment]
@romi1502 that's actually an interesting approach. Have you checked if this improves the evaluation scores?

**Comment by romi1502** [comment]
Not yet, but i suspect it won't change much as high frequency have very low energy and BSS eval metrics are energy based. Will try to do soon :).

**Comment by xomega100** [comment]
how do you actually change the F value in a command? ive read about it but im clueless cos there are no examples i can learn from.

**Comment by lesecs** [comment]
Where i can fins json-config?
I Try in  spleeter but Neverfind. Can you tell me where hé us
Ty
