### ISSUE TITLE
[Feature] Audacity/VST Integration

### ISSUE THREAD

**Issue by cybertheory** [deezer/spleeter#181]
## Description

I have been in contact with the Audacity Dev Team and we have been discussing how to integrate Spleeter into free/open-source DAWs. We want to suggest that Spleeter have a c++ sister version that could be ported as a VST plugin or ported into full integration in Audacity with ease. If the Spleeter team could please either translate the data processing to c++ or give a clear rundown as to what the data processing steps are so we could create a c++ version using the pre-trained models it would be most appreciated.

## Additional information

We were also looking into legal and licensing disputes. It seems that a VST plugin would be external and thus be open to use for any DAW regardless of license.

**Comment by mmoussallam** [comment]
Hi there,

Thanks for the suggestion, we have started a discussion about it: https://github.com/deezer/spleeter/issues/155 it seems to be doable, feel free to join the conversion there.

**Comment by gvne** [comment]
I know this issue is already a couple of month old but if you are still interested in integrating spleeter in a VST, I am working on a C++ port of the tech (see [here](https://github.com/gvne/spleeterpp)).
Lately, I integrated it in a simple [JUCE project](https://github.com/gvne/urSpleeter) and thought it may help you.  

The next step is to [enable in-line processing](https://github.com/gvne/spleeterpp/issues/1) of the signal. I am working on this at the moment but the task isn't trivial.

**Comment by mmoussallam** [comment]
Anyone interested in this can have a look at the great work of @gvne described in #276
