### ISSUE TITLE
[Discussion] about the softmax final layer

### ISSUE THREAD

**Issue by aliutkus** [deezer/spleeter#205]
Hi,

Is the final softmax layer some idea you came up with, or did you see this elsewhere ?

it looks like a pretty cool idea and seems to help, I wonder if it's published somewhere

best

**Comment by romi1502** [comment]
Hi @aliutkus,
I don't remember having seen the idea anywhere in the literature but it seems so obvious that someone has probably already done it somewhere. We actually only use the softmax layer on the 5 stems model. It seemed that it helped the piano model converging (otherwise, it was very usual that the model got stuck in a local minimum). I'm not fully convinced it improves separation results though. We can talk about this more in details offline :).
