### ISSUE TITLE
[Discussion] Example on how to change bitrate

### ISSUE THREAD

**Issue by Waffled-II** [deezer/spleeter#214]
I'm new to Python and don't know much. I know that in the recent release of Spleeter bitrate options were introduced. I used pip uninstall, deleted other info from it, and then reinstalled it so I could have it (please tell me if I did it wrong). I tried using the command as so 
spleeter separate -i 'SEARCHLIGHT.mp3'  -p spleeter:5stems -b 320k -o splits
however nothing is changing as the bitrate is still 128. is there an example on how this should work?

**Comment by mmoussallam** [comment]
Hi @Waffled-II 

The bitrate options is actually passed on to the `ffmpeg` library that will handle the writing of the output files. Depending on your FFmpeg installation the exact command may vary. You can have a look at their documentation: https://trac.ffmpeg.org/wiki/Encode/MP3 to get an idea. 

My 2 cents will be to remove the `k``in your `-b 320k` argument and see if it works.

Good luck

**Comment by romi1502** [comment]
Hi,
with the current version, setting the bitrate seems to work correctly:
```bash
spleeter separate -i audio_example.mp3 -p spleeter:5stems -b 320k -c mp3 -o splits
```
This command outputs mp3 audio files with bitrate 320kpbs.
Be sure to use the `-c mp3` option to get the output in mp3. Without the `-c` option, the default output file type is wav, with PCM encoding, for which the `-b 320k` option has no effect.

**Comment by Mixerrog** [comment]
Is there a way to convert output files to flac instead of wav files to save Hard Drive space? I input flac files & they are converted to wav files on output always. 

Thanks, Rog

    On Monday, January 13, 2020, 9:07:42 AM MST, Romain Hennequin <notifications@github.com> wrote:  
 
 
Hi,
with the current version, setting the bitrate seems to work correctly:
spleeter separate -i audio_example.mp3 -p spleeter:5stems -b 320k -c mp3 -o splits
This command outputs mp3 audio files with bitrate 320kpbs.
Be sure to use the -c mp3 option to get the output in mp3. Without the -c option, the default output file type is wav, with PCM encoding, for which the -b 320k option has no effect.
