### ISSUE TITLE
[Discussion] increasing extracted vocal quality

### ISSUE THREAD

**Issue by davidhin** [deezer/spleeter#234]
Many high-quality acapellas can be found online. The vocals extracted by spleeter can sometimes be a bit noisy or artifact-y. Would it be worth looking into training a model to "denoise" the vocals, similar to how an image may be denoised, using Spleeter as the "noise" introducing mechanism? I know this would be a hacky downstream task, but it could be useful for pure convenience purposes (music production) at the moment. 

My experience in machine learning is all in NLP, so I'm not too sure about the progress of AI in audio/music tasks; however, if this idea is reasonable I would be happy to look more into this, particularly if there are any starting points / relevant research.

**Comment by HandsomeDevilv112** [comment]
I'm having this as well, I've been looking into using audacity to try to reduce the "echo" quality to the extracted vocals. However, I haven't found anything solid at this time.

**Comment by mmoussallam** [comment]
Hi @davidhin 

Reducing separation artefacts is actually an active research topic.. and it's not easy at all :) if you're interested in current trends you will find very good pointers [here](https://mip-frontiers.eu/2019/11/13/waspaa.html).

**Comment by redbar0n** [comment]
any luck so far @HandsomeDevilv112 ?

I'm trying to do the same, in Audacity, but haven't had much luck. It should be possible using _some_ kind of tool, since [Audo.ai](https://audo.ai/) uses spleeter and is able to remove the echo / machine / chromatic artefacts from the spleeter vocals (as observed when I tried their demo on a small clip).
