### ISSUE TITLE
Install with standard Python, not conda

### ISSUE THREAD

**Issue by goa867** [deezer/spleeter#24]
Hi, I'm not a big fan of conda, would you have a install "howto" for standard Python? Thank you very much.

**Comment by goa867** [comment]
Sorry @Faylixe, I should have mentioned I have already carefully read https://github.com/deezer/spleeter/wiki/1.-Installation#using-pip :

> pip based install method does not support GPU. If you need to run Spleeter on GPU devices, we recommend an installation with conda or to use the provided GPU Docker image.

What I wanted to say is that there is no 'intrinsic' reason for which it wouldn't work (with GPU) with standard Python. Could we maybe let this open in the case someone using standard Python can share a method working with standard Python?

**Comment by Faylixe** [comment]
> Sorry @Faylixe, I should have mentioned I have already carefully read https://github.com/deezer/spleeter/wiki/1.-Installation#using-pip :
> 
> > pip based install method does not support GPU. If you need to run Spleeter on GPU devices, we recommend an installation with conda or to use the provided GPU Docker image.
> 
> What I wanted to say is that there is no 'intrinsic' reason for which it wouldn't work (with GPU) with standard Python. Could we maybe let this open in the case someone using standard Python can share a method working with standard Python?

Better that way :). Indeed we have no reason to do so, we will publish a `spleeter-gpu` package on `PyPi` with the appropriate `tensorflow-gpu` dependency soon. We prefer redirect GPU users to `Conda` since it will handle all GPU dependencies such as _CUDA_ which can not be automatically installed with `pip`.

Expert user can still install standard `spleeter` package with `pip`, then manually install `tensorflow-gpu` and it should work as expected (until we did publish a proper tested GPU package though we will not handle support ourselves).
