### ISSUE TITLE
[Discussion] Bad training results

### ISSUE THREAD

**Issue by aidv** [deezer/spleeter#286]
As title says.

Why after I've trained a model, the two resulting stems kind of bleed in to each other.

Both of them vaguely have audio from each other.

**Comment by mmoussallam** [comment]
Hi @aidv 

Short answer: Source separation is hard :)

Since we don't know your data it's impossible to say what's possibly going wrong or not. You may want to analyze your learning process, specifically whether it[ overfits or underfits](https://www.tensorflow.org/tutorials/keras/overfit_and_underfit) your training data.  If your dataset is not so large, it's also probably to fine-tune an existing pre-trained model rather that trying to train from scratch.

Finally, don't hesitate to evaluate your trained model on public datasets such as musdb. In any case, look for the file where the separation results are not good and try to understand why (mixing conditions ? unbalance of this genre in your dataset ? ...)
As always in machine learning: errors are more interesting than successes.

**Comment by aidv** [comment]
@mmoussallam it's very hard, seems like.

Would you say that difference in amplitude makes a huge difference?

Let's say that the volume of the input stems don't perfectly match the volume of the stems when mixed down.

Will this significantly affect the training results?
