### ISSUE TITLE
[Discussion] How to finetune “2stems-finetune” model with "F":1536

### ISSUE THREAD

**Issue by blackpaintedman** [deezer/spleeter#304]
Grettings. I tried trainning from checkpoint from "2stems-finetune" model, with my own vocals-accompaniment dataset(44.1khz, stereo). 

It works fine with "F":1024. Though reports error when I raise "F" to higher value like 1536. the error info as follows:

    (0) Invalid argument: assertion failed: [Need value.shape >= size, got ] [624 3072 2] [512 4608 2]
         [[{{node random_crop/Assert/Assert}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_2768]]
    (1) Invalid argument: assertion failed: [Need value.shape >= size, got ] [624 3072 2] [512 4608 2]

It seems that the "2stem-finetune" itself is trained on "F":1024, is there any way I can finetune it with higher "F" value, so I can take advantage of the information above 11khz from my own datasets?

Any idea appreciated!

**Comment by romi1502** [comment]
Hi @blackpaintedman 
I've got no problems fine tuning the 2 stems model with various value of F (1536, 1024). I think it is related to dataset caching.  
If you change F, you must recompute the cache otherwise, if you change from 1024 to 1536, it will generate such a wrong shape Error. 

For recomputing the cache you can either erase it (check the value of the field `training_cache` and `validation_cache` to know where it is located) or change the value of `training_cache` and `validation_cache` in your config file.
