### ISSUE TITLE
[Discussion] JOSS review point: installation instructions

### ISSUE THREAD

**Issue by bmcfee** [deezer/spleeter#307]
Hey spleeter devs, I'm a reviewer on your (JOSS submission](https://github.com/openjournals/joss-reviews/issues/2154)

Working down the checklist, I had a question about your [installation instructions](https://github.com/deezer/spleeter#quick-start).  They appear to be correct (ie it works), but I'm confused by the instruction to both clone the repo and install from conda-forge.  I assume this is only written this way to ensure that the demo track is available for running the test command.

I might suggest breaking this up into more explicit sections for installing the package (for use), installing for development (git clone), and testing on an example audio file.

**Comment by mmoussallam** [comment]
Hi @bmcfee 

First of all, thanks a lot for taking upon your time to review our submission, especially considering the worldwide situation going on.

Indeed you're right that the cloning is not really needed now. In a first version we were also locally building a `conda` env from a cloned file. But since we've ported spleeter to conda-forge we should probably update the documentation accordingly.

I'm letting this issue open until we do so.

Stay safe and I hope you'll have some fun in using spleeter.

**Comment by romi1502** [comment]
Hi @bmcfee 
Thank you for the suggestion. Indeed, it was unclear that the `git clone` was only for downloading the audio demo file.
We updated the readme for making the `Quick start instructions` more explicit by adding comments and replacing the `git clone` by a `wget`.
Let us know if you feel it may be improved further.
