### ISSUE TITLE
[Discussion] Discord Server dedicated to Spleeter

### ISSUE THREAD

**Issue by Zcooger** [deezer/spleeter#315]
Hello, I create this ticket to suggest creating a Discord Server for Spleeter community.
I base this idea on the other projects that decided to use it besides GitHub tickets for more flexible discussion like:
- Domesday86.
- Teletext Group.
- OpenLoco.

Btw. Many thanks for this project. Listetning to non-existent instrumentals is a pleasure.

**Comment by aidv** [comment]
I'd be down for it

**Comment by avantguard** [comment]
This would be great!

**Comment by Richard3234sa** [comment]
Spleeter is doesn't work for me, this is shit

**Comment by Zcooger** [comment]
@Richard3234sa Did you try Spleeter GUI?
https://youtu.be/bdNzVPLzOLE

**Comment by mmoussallam** [comment]
Hi all,

We don't really have enough resources to start and maintain yet another communication channel around this project, so the Discord is not going to happen anytime soon, at least not hosted by us.

To @Richard3234sa thanks for this very constructive feedback. A quick reminder though: this is a free, open-source project, not a software you bought. We delivered and maintain it for free with the hope that it'll be useful to researchers and musicians. It appears to work just fine for thousands of them, and not for you. I'm very sorry about that but numbers here do not seem to indicate that the problem is on the code. 

There's a pretty extensive [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ) here to help (I'm sure that you read it in full to find a solution) and we have already received more than 300 issues that we try to address, at least when they are correctly formatted and come with the minimum of politeness and decency. 

Have a great Easter holidays

**Comment by Zcooger** [comment]
Ok, so I decided to start an Spleeter Discord server. Feel free to include it in the description.
We welcome all from the community here:
https://discord.gg/j67mhEj
