### ISSUE TITLE
[Discussion] Difference between librosa and tensorflow for stft_backend?

### ISSUE THREAD

**Issue by JeffreyCA** [deezer/spleeter#348]
At a high level, what are the differences between the two backends?

**Comment by alreadytaikeune** [comment]
Librosa is another library completely separate from tensorflow. When using librosa as the stft backend, all the stft computations are done by librosa and not tensorflow, meaning that we chop the tensorflow graph and use different stubs were instead of feeding waveforms and leaving all the processing to tensorflow, we feed spectrograms (and also get spectrograms back).
The reason we do that is that we have noticed that the stft operations as implemented by tensorflow on CPU were extremely slow and very memory consuming. It is still the best option on GPU though, hence why we wanted to provide an alternative when executing on CPU.

**Comment by Saxamos** [comment]
By "best option on GPU" you mean that the split quality will be higher with tensorflow?
