### ISSUE TITLE
Is there any way to enhance the quality of output audio?

### ISSUE THREAD

**Issue by Ferrasil** [deezer/spleeter#37]
I read your Wiki tab, but didn't find is there any way to upgrade the result separations quality (maybe using more power of my pc or something?). Because it sounds like it can produce much more clear sound or am I wrong? Thanks

**Comment by awesomer** [comment]
I am not associated with the project, and don't know what you're referring to in terms of "quality," but it's worth noting that the default settings cut all frequencies above 11khz in the output, and this makes the results sound more muffled (albeit more accurately separated) than they otherwise might.

See https://github.com/deezer/spleeter/issues/2#issuecomment-548798493 for more details.

**Comment by Ferrasil** [comment]
> I am not associated with the project, and don't know what you're referring to in terms of "quality," but it's worth noting that the default settings cut all frequencies above 11khz in the output, and this makes the results sound more muffled (albeit more accurately separated) than they otherwise might.
> 
> See [#2 (comment)](https://github.com/deezer/spleeter/issues/2#issuecomment-548798493) for more details.

thanks , that's it!
