### ISSUE TITLE
[Bug] unrecognized arguements: spleeter:5stems

### ISSUE THREAD

**Issue by JohnSmith2007** [deezer/spleeter#372]
## Description
I've been dealing with several errors with this program for the past month, and i thought i finally figured it out. apparently i was wrong.

## Step to reproduce
1. Installed using Conda
2. Run as python -m spleeter separate -i C:\Users\smcco\Music\Customs i've made\Comin_in_Hot.mp3 -c mp3 spleeter:5stems -o /output/C:\Users\smcco\Music\
3. Got spleeter: error: unrecognized arguments: spleeter:5stems

## Output

```bash
(base) C:\Users\smcco>python -m spleeter separate -i C:\Users\smcco\Music\Customs i've made\Comin_in_Hot.mp3 -c mp3 spleeter:5stems -o /output/C:\Users\smcco\Music\
usage: spleeter [-h] {separate,train,evaluate} ...
spleeter: error: unrecognized arguments: spleeter:5stems
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Windows |
| Installation type | Conda |
| RAM available     | 16GB |
| Hardware spec     | GPU: nVIDIA GeForce 1050 Ti, Intel UHD Graphics 630 / CPU: Intel i5-8300 |

## Additional context
I think this program hates me.

**Comment by mmoussallam** [comment]
Hi @JohnSmith2007 

Could you please look at the [documentation](https://github.com/deezer/spleeter/wiki/2.-Getting-started#using-5stems-model) ? you have (once again) made an error in your command syntax ( a missing `-p`) it's not an issue with the program.

Please be aware that creating bug reports like this is time consuming on our side. Before opening a ticket please make sure that your problem is not in your command or already solved in the FAQ.
