### ISSUE TITLE
[Discussion] updating Python dependencies

### ISSUE THREAD

**Issue by flriancu** [deezer/spleeter#493]
Some Python packages listed in `setup.py` are a little bit old:

- pandas is now `1.1.2` as opposed to `0.25.1`
- librosa is now `0.8.0` as opposed to `0.7.2`
    - it now requires `numba==0.48.0` for itself, so unless you're using numba in the actual project, you can remove it

Also, I think you can:
- safely replace all current `==` conditions to `>=` for all items in `install_requires`
- maybe add a condition like `tensorflow >=1.14, <2.0` so that it will work with tensorflow 1.14 and avoid [issues like this](https://stackoverflow.com/questions/61491893/i-cannot-install-tensorflow-version-1-15-through-pip)
- maybe add support for python 3.8 or even the [upcoming 3.9](https://docs.python.org/3.9/whatsnew/3.9.html)

**Comment by romi1502** [comment]
Thank you for reporting this dependencies issue.
> pandas is now 1.1.2 as opposed to 0.25.1

Yes, the version we use is a bit a old and it should not be a big deal to update. I'll have a look at it.

> librosa is now 0.8.0 as opposed to 0.7.2
it now requires numba==0.48.0 for itself, so unless you're using numba in the actual project, you can remove it

Definitely. The hard numba dependency was a hot fix while waiting for librosa 0.8.0. We'll consider switching to `0.8.0` shortly too.

> safely replace all current == conditions to >= for all items in install_requires

For this one, I disagree: it may make bug appear just because of updates or change of API in the dependencies. So I think it is a better practice to only consider a set of predefined versions and never use `>=`.

> maybe add a condition like tensorflow >=1.14, <2.0 so that it will work with tensorflow 1.14 and avoid issues like this
I've to double check this one, but this seems fine.

> maybe add support for python 3.8 or even the upcoming 3.9
We're considering support for python 3.8 but for that we need to support tensorflow 2 first (as tensorflow 1 is not compatible with python 3.8). It should come shortly.

**Comment by flriancu** [comment]
> So I think it is a better practice to only consider a set of predefined versions

Fair enough!

> we need to support tensorflow 2 first [...] It should come shortly.

To confirm, is it on the `tf2` branch?
