### ISSUE TITLE
[Feature] Installing and running Spleeter on Windows

### ISSUE THREAD

**Issue by OSINTAI** [deezer/spleeter#502]
## Description

Installing and running Spleeter on Windows (Python 3.7)

`virtualenv spleeterenv && cd spleeterenv/Scripts/ && activate
`
EDIT: 

`cd ..`

Clone Spleeter repo in the environment:

`git clone https://github.com/deezer/spleeter.git`

cd spleeter

`pip install . && pip install pytest pytest-xdist
`
Also install 

`pip install musdb
`
`pip install museval
`
Then:

`python setup.py install`

It worked

Ex: `spleeter separate -i song.mp3 -o audio_output -p spleeter:5stems `

**Comment by HatScripts** [comment]
Hey there, I'm trying to follow these steps with a fresh installation of Python 3.8.5 and spleeter 2.0.

Firstly, I could be wrong, but I think there's meant to be a `cd ..` after the first line, because otherwise the `pip install .` gives:
```
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

But then even when I change the working directory to be the "spleeterenv" folder, the `pip install .` gives me this error:
```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.0 (from spleeter==2.0) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.0 (from spleeter==2.0)
```

I also tried with spleeter 1.4 but it seems it doesn't support Python version 3.8 or higher:
```
ERROR: Package 'spleeter' requires a different Python: 3.8.5 not in '>=3.6, <3.8'
```

Any idea what I'm doing wrong?

**Comment by OSINTAI** [comment]
You are right.
I will re-edit the steps.

**Comment by mmoussallam** [comment]
Hi @OSINTAI 

I'm not sure why you would need to open this issue, does the standard installation guide not work for your setup ?

**Comment by OSINTAI** [comment]
Hi @mmoussallam 
It did not work the first time and I installed `musdb` and `museval` as they were missing. I just wanted to help in case someone has the same issue as I did. I have put it under enhancement. :)

**Comment by mmoussallam** [comment]
Thanks for the initiative :+1:  but I'm wondering because basically `musdb` `museval` are only useful for training and advanced usage and not required to just run spleeter
