### ISSUE TITLE
A question about the length of separation of audio files

### ISSUE THREAD

**Issue by mtz1992** [deezer/spleeter#528]
Excuse me.why do I use a 20 minute audio file,but output is two  10 minute audio files,when I use 2stems model.

**Comment by romi1502** [comment]
The maximal duration of the input to be processed can be set with the `-d` option (expressed in seconds):
```bash 
spleeter separate -i input_audio_file.wav -d 300 
```
The default duration is set to 600s (10 minutes), which is why you get 10 minute audio outputs. 
You can set it with a higher value but be aware that it may require quite a lot of RAM and produce Out Of Memory errors.
