### ISSUE TITLE
[Discussion] Changelog

### ISSUE THREAD

**Issue by Christilut** [deezer/spleeter#541]
I'm just wondering if there is a changelog, I can't seem to find it.

Also I'm a bit confused about the versions everywhere because currently I'm seeing this:
- Version 1.4.0 on github release page
- Version 2.0.2 on pip
- Version 1.5.3 on conda

**Comment by Faylixe** [comment]
Hello, I don’t think we have maintained a Changelog so far unfortunately. The GitHub release is only here to provide model storage , it haven’t been updated since first release. The pip is the most up to date version and we faced some issue with conda on latest releases due to TF2 unavailability on condaforge, we are currently changing that and will provide an update to the documentation once it is done (probably in January)

**Comment by mmoussallam** [comment]
Hello @Christilut 

We do have a [Changelog](https://github.com/deezer/spleeter/blob/master/CHANGELOG.md) but indeed there are different versions:
* the github release is stuck to 1.4 but mostly because it's just storing the pre-trained models, and those haven't changed
* the pip version is the most up to date
* the conda version is stuck a bit behind because of tensorflow not being easily installed on all platforms
