### ISSUE TITLE
[Discussion] Docker researchdeezer/spleeter VS deezer/spleeter

### ISSUE THREAD

**Issue by just-jeb** [deezer/spleeter#545]
Hey folks. I'm struggling to understand the difference between `researchdeezer/spleeter` and `deezer/spleeter` Docker images.  
On one hand I see that your [CI](https://github.com/deezer/spleeter/blob/master/.github/workflows/docker.yml) builds, tests and pushes the `deezer/spleeter`. 
On the other, I see that [spleeter-model](https://github.com/deezer/spleeter/blob/master/docker/spleeter-model.dockerfile) Docker file uses `researchdeezer/spleeter` as a base image. And I have no idea where the  `researchdeezer/spleeter` is coming from (couldn't find it in the repo).  

Can you please straighten it up for me?  

If I were to use Spleeter in Docker (or, alternatively, create another image based on one of the Spleeter images), which image would I use? Would it be `researchdeezer/spleeter` or `deezer/spleeter`?
And what is the benefit of using `conda` image over `pyton` image and vise versa?

Thanks!

**Comment by Faylixe** [comment]
Actually when we released Spleeter our official account `Deezer` on Dockerhub were lost, so we temporary created a `researchdeezer` namespace. Since we managed to recover the official account we migrate image to `deezer` namespace, we are currently upgrading all Docker images so the repository will be up to date with latest Spleeter version.
