### ISSUE TITLE
isolating a guitar solo

### ISSUE THREAD

**Issue by yamtssfa** [deezer/spleeter#551]
Goal is to create a track without the guitar solo.
Would spleeter have the ability to isolate a guitar solo from a song if a training track was created consisting of just the actual guitar solo (performed and recorded by me as well as possible)?

**Comment by romi1502** [comment]
Hi @yamtssfa,
thank you for your question.
Isolating a guitar solo is quite hard per se, because the system needs to be able to distinguish what can be considered as a solo and what cannot and then to be able to predict the role of the guitar within the track.
The released for spleeter, based on U-nets, were not trained to perform such a task and I doubt they would be able to it well if properly trained. But the only way to check is to try :).
If you want to train such a system, you will need much more than a single isolated solo guitar and backing track.
