### ISSUE TITLE
[Discussion] Train pre-trained model on new training set

### ISSUE THREAD

**Issue by Danngonz3** [deezer/spleeter#598]
Is there a way to continue training the already trained model on my own data, essentially giving it more example to learn from?

**Comment by romi1502** [comment]
Hi @Danngonz3.
For continuing training of a pre-trained model, you can use the `fine-tune` models available on the [release page](https://github.com/deezer/spleeter/releases/tag/v1.4.0).

You'll have to:
* download the model from the [release page](https://github.com/deezer/spleeter/releases/tag/v1.4.0).
* use a JSON configuration that looks like this (and that we'll assume to be named `4stems-finetune.json`):
```json
{
    "train_csv": "training_dataset.csv",
    "validation_csv": "validation_dataset.csv",
    "model_dir": "4stems-finetune",
    "mix_name": "mix",
    "instrument_list": ["vocals", "drums", "bass", "other"],
    "sample_rate":44100,
    "frame_length":4096,
    "frame_step":1024,
    "T":512,
    "F":1024,
    "n_channels":2,
    "separation_exponent":2,
    "mask_extension":"zeros",
    "learning_rate": 1e-4,
    "batch_size":4,
    "training_cache":"cache/training_cache",
    "validation_cache":"cache/validation_cache",
    "train_max_steps": 2000000,
    "throttle_secs":600,
    "random_seed":3,
    "save_checkpoints_steps":300,
    "save_summary_steps":5,
    "model":{
        "type":"unet.unet",
        "params":{
               "conv_activation":"ELU",
               "deconv_activation":"ELU"
        }
    }
}
```
You can then run training with:
```bash
spleeter train -p 4stems-finetune.json -d <path/to/dataset/>
```

Be sure to:
* put the model in the direction given by `model_dir` in the configuration file (namely `4stems-finetune` in the provided example)
* describe the audio samples of your training and validation dataset within the file given by  the `train_csv` and `validation_csv` in the configuration file (namely "training_dataset.csv" and "validation_dataset.csv"). This must have the format of [this example file](https://github.com/deezer/spleeter/blob/master/configs/musdb_train.csv).
* Chose a `train_max_steps` that is higher than the number of steps the model was already trained (otherwise will stop straight away).

**Comment by Danngonz3** [comment]
Thank you Romi!!!
