### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by ChenJingZhuo** [deezer/spleeter#601]
![image](https://user-images.githubusercontent.com/36926346/113030487-3bebf580-91c0-11eb-8e5f-6b31f66de245.png)

![image](https://user-images.githubusercontent.com/36926346/113030708-7786bf80-91c0-11eb-9d02-b657097d945c.png)

How to fix it up?

**Comment by romi1502** [comment]
Hi @ChenJingZhuo,
It seems you're using a quite old version of spleeter, since the latest version does no longer use the tensorflow.contrib.signal module (which indeed disappeared in recent tensorflow version). 
Please update to the latest spleeter version, or if you really need to keep the old version, make sure you use a compatible tensorflow version.
