### ISSUE TITLE
[Discussion] Isolating guitars?

### ISSUE THREAD

**Issue by ibigbug** [deezer/spleeter#619]
Awesome project!

I think it'd be awesome to also have a way to isolate guitar tracks.

Found some related discussions:

- #3 
- #62 
- #551 

Right now it works perfectly with the Bass track.

Assuming Bass usually has a relatively "low frequency" in terms of the sound not sure if that helps the model to detect it's a Bass sound in the frequency domain(if FFT is used)(trying to make sense, but not sure I'm understanding this at all).

Wonder is it possible to ("easily") isolate the Lead/Rhythm guitar for rock songs?

### Update

It seems using 5 stems and the "other" track contains the guitar tracks for a rock song that I tried.

Though the "volume" of the sound doesn't sound consistent.

**Comment by romi1502** [comment]
Hi @ibigbug
indeed it would be awesome. We actually tried to train 5 stems models were the fifth stem was guitar instead of piano before releasing spleeter, but we got quite unsatisfactory results. We won't have time to work on new models in the near future, but you can also try to train your own model to separate guitar if you have appropriate data.

Regarding your "volume" issue, note that stems should sum up to the mix, so if the volume of a stem seems quite different from the volume in the mix, this is probably because the corresponding instrument was not properly separated and part of it should remain in the other stems.
