### ISSUE TITLE
[Bug] Can't install because of dependency to Tensorflow 2.3

### ISSUE THREAD

**Issue by OlafKnolaf** [deezer/spleeter#640]
Current tensorflow version is 2.5

**Comment by ab10002** [comment]
+1

**Comment by romi1502** [comment]
Hi @OlafKnolaf, @ab10002 
Indeed, spleeter currently depends on tensorflow 2.3. We may update the dependency to 2.5 in the near future, but we need to test it a bit further before.
In the meantime, you can either use a virtual env with tensorflow 2.3, or install spleeter from source updating the pyproject.toml file (set tensorflow version to 2.5 and numpy version to 1.19.2), and running `poetry install`.
It should work, but hasn't  been extensively tested yet.

**Comment by iotku** [comment]
Expanding on this a bit, pip under Python 3.9 won't install tensorflow 2.3 (as currently required by spleeter) because tensorflow 2.5 is the least supported version under Python 3.9.

A temporary workaround if you just want to install is to downgrade to python 3.8, but that might not be practical for everyone.

**Comment by mmoussallam** [comment]
Hi everyone, we've just released a new version (2.3.0) that should be compatible with tensorflow  2.5. Let us know if you have any issue
