### ISSUE TITLE
[Bug] Spleeter only processes the first minute of audio

### ISSUE THREAD

**Issue by LoboMetalurgico** [deezer/spleeter#673]
- [x] I didn't find a similar issue already open.
- [x] I read the documentation (README AND Wiki)
- [x] I have installed FFMpeg
- [x] My problem is related to Spleeter only, not a derivative product (such as Webapplication, or GUI provided by others)

## Description

When trying to separate the music using any of the tracks (2/4/5 stems) the spleeter processes the command normally, but the final audio is only 1 minute long.

## Step to reproduce

1. Installed using `pip`
2. Run `python3 -m spleeter separate -p spleeter:2stems -o output audio.mp3`
3. Receive "succesfully" message
4. The final audio is just 1 minute

## Output

```bash
INFO:spleeter:File output/audio/vocals.wav written succesfully
INFO:spleeter:File output/audio/accompaniment.wav written succesfully
```

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Linux (Kubuntu 20.04) |
| Installation type | pip             |
| RAM available     | 8GB                             |
| Hardware spec     | CPU (I5 3ª Generation)            |

## Additional context

It started happening after the September 3rd update.

**Comment by tahomi-epam** [comment]
I have similar issue, but have 10 minutes final audio.

**Comment by tahomi-idq** [comment]
@LoboMetalurgico I found something maybe will be useful to you. If you pass the flag -d with duration in seconds, in result you will have final audio with duration you passed as argument.

`spleeter separate -d 14400 -o output 'some_long_file.mp3'`, where 14400 is timing in seconds. 

But when I tried it with 4 hour audio, linux started lagging very badly and force quit job. 
With 13 minutes audio it worked ok.

**Comment by LoboMetalurgico** [comment]
Unfortunately, it didn't work :(

**Comment by romi1502** [comment]
Hi @LoboMetalurgico
this is very strange. Do you have the same issue on several audio files ?
@tahomi-idq, the `-d` option indeed default to 600 (=10 minutes), to avoid memory issue (memory usage is proportional to the file length, which is something we have been wanting to fix for a long time but haven't fixed yet). So setting it to 4h is indeed likely to results in strong memory usage that may overcome the available RAM. It is then quite likely that your system starts to swap heavily and explain the lag you experienced (otherwise, you'll get an OOM error). So if you need to process very long audio files, I would recommend to chop them in slightly overlapping shorter chunks (~10 min max, depending on your available RAM) before processing them.

**Comment by LoboMetalurgico** [comment]
Sorry for taking so long to respond. It looks like it was an error when you updated. After reinstalling, everything went back to normal.
