### ISSUE TITLE
ValueError: need at most 63 handles, got a sequence of length 82

### ISSUE THREAD

**Issue by Gallion** [deezer/spleeter#684]
> spleeter separate -B tensorflow -b 360k -o "C:\Users\ADMINI1\AppData\Local\Temp\tmprwjp9551" "C:\Users\ADMINI1\AppData\Local\Temp\tmprwjp9551\pt1.m4a"
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 519, in _handle_workers
>     cls._wait_for_updates(current_sentinels, change_notifier)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
>     wait(sentinels, timeout=timeout)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 884, in wait
>     ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
>     res = _winapi.WaitForMultipleObjects(L, False, timeout)
> ValueError: need at most 63 handles, got a sequence of length 82
> INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
> INFO:spleeter:Validating archive checksum
> INFO:spleeter:Extracting downloaded 2stems archive
> INFO:spleeter:2stems model file(s) extracted
> INFO:spleeter:File C:\Users\ADMINI1\AppData\Local\Temp\tmprwjp9551\pt1/vocals.wav written succesfully
> INFO:spleeter:File C:\Users\ADMINI1\AppData\Local\Temp\tmprwjp9551\pt1/accompaniment.wav written succesfully

The program will hang at this point.

This issue is a Windows-specific issue that happens on systems with over ~61 logical cores.
It is related to https://bugs.python.org/issue26903. It should have been fixed in 3.9.7 but it is still happening on 3.9.9.
Limiting the number of threads may fix the issue.

**Comment by johndpope** [comment]
Readme says don’t use 3.9
You can get around this using miniconda.

**Comment by Gallion** [comment]
The bug report I linked says that the issue has been existing since at least 3.5.1. Not using 3.9 as you suggest, does not help.
I don't see where the readme says not to use 3.9.

**Comment by johndpope** [comment]
my bad- it's in the FAQ 
https://github.com/deezer/spleeter/wiki/5.-FAQ

**Comment by Gallion** [comment]
I'm using 2.3.0 which uses Tensorflow 2.5 so that's not relevant.

**Comment by mmoussallam** [comment]
Hi @Gallion 

It'll be quite hard for us to replicate, not having access to a windows machine with that much logical cores. Based on the logs you shared, the separation itself seems to be ok and the error only happens at the very last stage of writing the output. Now we use parallel calls with the `multiprocess` module in order to save time when writing outputs, I suppose a workaround is to deactivate the multiprocess writing (e.g. you can comment out this line https://github.com/deezer/spleeter/blob/master/spleeter/separator.py#L124). Unfortunately this is not an option that you can set from the command line at the moment.

Also it's likely that this issue pops for many other python packages using the `multiprocess` module so hopefully there's a solution to your problem out there, possibly just with setting a correct value for some environment variable.

Best of luck

**Comment by Gallion** [comment]
I made a pull request to fix the issue.

**Comment by Gallion** [comment]
I fixed the issue rather than disabling multithreading. I cannot do the testing with poetry however so I didn't make a pull request.
