### ISSUE TITLE
Performance on GPU server

### ISSUE THREAD

**Issue by Sameerhesta** [deezer/spleeter#697]
## Description

I am facing an issue, I am splitting audio (Wav file) of 60 Seconds. it is taking almost 12 to 15 seconds either I am using CPU or GPU.
It is not splitting my file as faster as it is coated in the documentation:-

> 2 stems and 4 stems models have high performances on the musdb dataset. **Spleeter is also very fast as it can perform separation of audio files to 4 stems 100x faster than real-time when run on a GPU.**

Can anyone guide me to achieve a faster separation speed?

## Environment

|                   |                                 |
| ----------------- | ------------------------------- |
| OS                | Linux  |
| Installation type |  pip             |
| RAM available     | 16 GB                             |
| Hardware spec     | GPU 16 GB AWS instance g4dn.xlarge with Tesla T4 card |

**Comment by romi1502** [comment]
Hi @Sameerhesta,
you must be aware that model downloading + loading, is a quite important overhead which for a single track will be way longer than the actual separation.
Usually, if you're interested in speed, it is because either you have several files to separate (a batch or files), or because you want your separation system to provide quickly the separated results. In both case, the overhead becomes irrelevant because you only have to load the model once.
So if you have a batch of file to process, process them all at once. Using the `spleeter` CLI, it would look like:
```bash
spleeter separate file1.mp3 file2.mp3 file3.mp3 ... fileN.mp3
```
And if you want a system returning separated tracks as fast as they are separated, use the `Separator` object of the python API and only instantiate one.
