### ISSUE TITLE
[Discussion] Why the input of the model is 44kHz in config file

### ISSUE THREAD

**Issue by yzspku** [deezer/spleeter#734]
From [FAQ](https://github.com/deezer/spleeter/wiki/5.-FAQ#why-are-there-no-high-frequencies-in-the-generated-output-files-), we know the model was trained on 11kHz. But in separation [code](https://github.com/deezer/spleeter/blob/a1708143c5b45b20cc2779a2259814369d79ed52/spleeter/separator.py#L378), the input audio of the model is 44kHz (in the [config file](https://github.com/deezer/spleeter/blob/master/configs/4stems/base_config.json)). Is there a conflict here?

**Comment by romi1502** [comment]
Hi @yzspku,
this is a bit more complex than that. As explained in the FAQ, the model was actually not trained on 11kHz but up to 11kHz on spectrograms computed from signal sampled at 44.1kHz (this parameter can be changed for training a system for scratch, but should not be changed at inference time).
So the idea is that input (mix) and target (separated instruments) spectrograms are computed on 44.1kHz signal, so they have frequencies up to 44.1/2 = 22.05kHz. But for memory efficiency reason, the spectrogram were trimmed at 11kHz before training. The advantage of doing that instead of processing signals sampled with a lower frequency is that it still makes it possible to perform the separation at frequencies up to 22.05kHz by extending the output spectrograms or masks (either with a post-hoc method by extending masks with the `mask_extension` parameter of the config file or just by extending the frequency reconstruction of the model by changing the `F` parameter of the config file at inference). For instance, setting F to `1536`, as done in the xx-16kHz configs, will process the signal up to 16kHz.
