### ISSUE TITLE
[Discussion] Fail to implement on GPU

### ISSUE THREAD

**Issue by Spencer19990618** [deezer/spleeter#743]
HI! I am completely a beginner for Spleeter.  I am recently trying to implement Spleeter on  GPU and check the total implementation time. 

I tried the command : time CUDA_VISIBLE_DEVICES='0'  spleeter separate -p spleeter:4stems -o eight4_GPU2  eight.wav .

but it didn't work, the it took almost the same time as the one without using "CUDA_VISIBLE_DEVICES='0' ".
 
better let me know any pre_work I might have skipped . Thx

**Comment by romi1502** [comment]
Hi @Spencer19990618,
For processing a single file, GPU may not bring much as most of the time is spent loading the model (which is not done on GPU). 
GPU is interesting if you're processing a lot of files at once with the CLI. Then model loading is done only once, and most of the time is spent in the computation.
Otherwise, you can use the python API and the Separator object. You create a single `Separator` object, that will prepare the model once and then every call to `separate` should be much faster using a GPU than a CPU.

**Comment by Spencer19990618** [comment]
@romi1502 Thanks ! I see. I will follow the [wiki](https://github.com/deezer/spleeter/wiki/4.-API-Reference) instructions  to build a Python API .
