### ISSUE TITLE
[Discussion] Processing generated waveforms in python

### ISSUE THREAD

**Issue by Carnageous** [deezer/spleeter#78]
I am using spleeter inside a python project and I want to work with the seperated waveforms.

When I, for example, have this code:
```
separator = Separator("spleeter:2")
    
audio_loader = get_default_audio_adapter()
sample_rate = 44100
waveform, _ = audio_loader.load(file, sample_rate=sample_rate)

prediction = separator.separate(waveform)
```
I am able to get the seperated waveforms as a dict of arrays. However, I want to treat the seperated waveforms as files (without saving them to the filesystem). Specificly, I want to send them over a HTTP connection, but idealy not as arrays but as base64 encoded mp3s.

Is it possible to convert these waveforms to an usable format without writing them to the filesystem? I cannot find a way to convert them into mp3/base64.

I know `audio_loader.load` returns the waveforms as well but even after looking into the code I cannot to find a way to deal with these files.

Sorry if this is obvious and I overlook something. Best regards!

**Comment by Faylixe** [comment]
Why not saving waveform to temporary file that would act as buffer ? 

Otherwise you need anyway to convert the waveform represented as a NumPy array into the target audio codec bytes to send it as in-memory audio file. You need to check dedicated Python library to do so which is out of the _Spleeter_ scope.
