### ISSUE TITLE
[Discussion] how does changing F from 1024 to 1536 affects the upper frequency processed (since the model was trained at 1024)?

### ISSUE THREAD

**Issue by netv1** [deezer/spleeter#784]
Hey guys, so after spending a LOT of time reading the other issues/posts here, the source code, the research papers and viewing the model I really can't understand how you can process more than 11025 Hz just by modifying the F parameter from 1024 to 1536 (or 2048 to process all of them).

The network is based on a U-Net which in turn is based on convolutions - which by their definition are FIXED. More specifically your inputs are 512 (time steps/hops - the T) x 1024 (bins in the FFT - the F) x 2 (channels) and the output is the same shape (the masks). So, even if you set F to 2048 you can only input a 1024-bin spectrogram to the model and also get a 1024 spectrogram back. Is the model somehow dynamic in this regard and also accepts/outputs 2048? If so, how/where? (in the source code I could not find it) I have read something about the model accepting multiples of 64 (or 128) for T (the time step) but can't figure it out how you can achieve something similar using F.

So, while I am familiar with both DSP (including STFT, windowing, reconstruction, ratio-masks, etc) and ML/DNN stuff this is still something I can't understand and I have the feeling that it's either something simple I'm missing or I may be getting more stupid with age :)

If someone can enlighten me on this I would really appreciate it

P.S. I know (and understand) about the mask extending (btw, it sounds a lot better if you use the average from the last/top 25% bins instead of all of them - it greatly reduces the artefacts/interferences) but I only care about the other solution in the FAQ - the changing of the F parameter

**Comment by romi1502** [comment]
Hi @netv1,
Actually, the inputs of spleeter pre-trained models are computed from spectrograms that are computed with a 4096-sample window on signal sampled @44.1kHz. Then, only the low-frequency part of the spectrogram, up to frequency bin F, is provided as input to the model. 
The models were trained with F=512 (which corresponds to ~11kHz), and then the inputs were 512x1024 matrices. 
As the model is fully convolutional, you can actually change the size of the input at inference time. For instance, if you choose F=1024, then you'll input a 1024x1024 matrix into the model, and the first dimension of the output of all the layers will be doubled, which will just result in doubling the first dimension of the output. There is only a constraint for the downsampling/upsampling layers of the network which require that both dimensions of the input are multiple of 2^6 (6 being the number of layers). So the models are perfectly able to take as input any matrix that fits this constraint.
The question you may then ask is about the ability of the model to output correct separation masks on frequency bands it was not trained for. It turned out that the models do a pretty decent job in those bands which is not totally surprising as you may have similar frequency patterns in those bands as the ones in bands they were trained on, though the explanation for this is not perfectly clear :).
