### ISSUE TITLE
Model Files in Docker

### ISSUE THREAD

**Issue by skeivani** [deezer/spleeter#92]
I use the following command to separate a single mp3 file:
**docker run -v $AUDIO_IN:/input -v $MODEL_DIRECTORY:/model -v $AUDIO_OUT:/output spleeter:gpu separate -i  /input/dr.mp3 -o /output -p spleeter:5stems**

It seems $MODEL_DIRECTORY:/model  is being ignored, because the model file gets downloaded again with each run.

**Comment by mickdekkers** [comment]
This happens because the model in the container is downloaded to `/workspace/spleeter/pretrained_models` by default, not to `/model`.

You need to either:
- change the directory it downloads the model to using the `MODEL_PATH` environment variable: `-e MODEL_PATH=/model`
- or change the docker volume to point to the right directory: `-v $MODEL_DIRECTORY:/workspace/spleeter/pretrained_models`

The `docker run` command [on the wiki](https://github.com/deezer/spleeter/wiki/2.-Getting-started#run-container) was recently updated to include the former.

See also https://github.com/deezer/spleeter/issues/6#issuecomment-549121927

Alternatively, you can build the image with the model included by editing the Dockerfile: https://github.com/deezer/spleeter/issues/6#issuecomment-553131487

**Comment by Faylixe** [comment]
@mickdekkers nailed it. In addition I would say that running the GPU image using `docker` command is pointless as it won't use GPU. If you want to use GPU with Docker you need to use either `nvidia-docker` command or `-runtime nvidia` parameter with `docker` command.
