### ISSUE TITLE
[Feature] offline app or a web based service

### ISSUE THREAD

**Issue by MohamedAliRashad** [deezer/spleeter#94]
## Description

It will be a nice feature to have a simple web interface for the project. Making it easier for non-IT users to benefit from.

## Additional information

I noticed a docker folder in the project, this will make the deployment easier already.

**Comment by Faylixe** [comment]
We won't provide that. You can search on Google to find project based on Spleeter.

**Comment by aidv** [comment]
Funny you say that. I'm actually working on a web based service and I'm about to upload everything tonight.
@Faylixe Would I infringe on any trademarks or copyrights or anything if I'd use the name "Spleeter" in my project name?
I want to make this available as an easy-to-use service for free.
Ads on the site are there to hopefully cover the hosting expenses.

**Comment by MohamedAliRashad** [comment]
> We won't provide that. You can search on Google to find project based on Spleeter.

I don't think you have to, i would suggest you leave the issue open for other developers like @aidv to complete it and add the app's link to the README at the end.

**Comment by aidv** [comment]
@MohamedAliRashad that's what I thought.
If @Faylixe could give me a green light to use `spleeter` as the name of the site we could all literally see this in action by tomorrow.

I am literally ready with my credit card in my hands right at this writing moment to purchase the domain and set everything up.

The service runs perfectly on my local network.

**Comment by Faylixe** [comment]
Such applications already exists actually. Since this project is under MIT licence you are free to use it and name it as you want (although I am not sure you can name the service `spleeter` as such, @mmoussallam, @romi1502, @alreadytaikeune ?).

The only thing that would not happen is that we won't provide any solution neither reference existing web application into this repository for legal reasons so we will keep the issue closed as it is out of the repository scope.

**Comment by aidv** [comment]
You're right, this is out of the repo scope.

@Faylixe but what is that application?

Would spleeter.<domain extension> be enough to differentiate the two? i.e `spleeter.xyz`.

Anyways, if anyone wants to know the address to the site, I've set up an empty repo called `spleeter.ai` on my github. Go there and star it and I'll update the README once I've launched the service.

The README will contain the URL to the service.

**Comment by Faylixe** [comment]
As I said, we won't communicate explicitly on nor reference third party solution based on _Spleeter_ for legal reason (regarding music copyright as this work is shared from a music streaming company). So please do not use this repository as a communication channel for your solution.

**Comment by mmoussallam** [comment]
Hi @aidv 

We can't give you a green light to use the name `spleeter`. People have been coming up with very creative other names for their web-based services :)

**Comment by aidv** [comment]
@mmoussallam yeah I expected a red light.
Me too, I came up with splitter.ai
Pretty creative, eh 😂

**Comment by doky** [comment]
Let's do a wiki page in the documentation referencing app using spleeter ? Sounds good no ? And please keep a disclaimer, spleeter is a research tool, we are happy if that can help music creation but let's keep respect of creators.

**Comment by aidv** [comment]
@doky Ofcourse, respect has to be given no matter what.

Sounds great.

I'd even go further than that and not only display apps that use Spleeter, but also display models that people train, maybe links to free resources that people provide, such as datasets. Since it is research, why not democratize all aspects of the project? But that can come later too.

Maybe put all of that in a readme file that people can pull and add to?
